export const doctors = [
  {
    id: 1,
    name: 'Dr. Aisha Kapoor',
    hospital: 'Nova Health Center',
    department: 'Cardiology',
    rating: 4.9,
    experience: '14 years',
    languages: ['English', 'Hindi'],
    fee: '$120',
    slots: ['9:00 AM', '10:45 AM', '2:15 PM'],
    avatar: 'https://images.unsplash.com/photo-1544723795-3fb6469f5b39?auto=format&fit=crop&w=200&q=80',
    bio: 'Advanced cardiac care with AI-assisted diagnostics for personalized heart health.',
  },
  {
    id: 2,
    name: 'Dr. Rohan Patel',
    hospital: 'Metro Medical Plaza',
    department: 'Neurology',
    rating: 4.8,
    experience: '12 years',
    languages: ['English', 'Hindi', 'Gujarati'],
    fee: '$140',
    slots: ['11:00 AM', '1:30 PM', '4:00 PM'],
    avatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=200&q=80',
    bio: 'Neuro care with compassion and evidence-driven treatment plans.',
  },
  {
    id: 3,
    name: 'Dr. Priya Reddy',
    hospital: 'Serene Skin Clinic',
    department: 'Dermatology',
    rating: 4.7,
    experience: '10 years',
    languages: ['English', 'Telugu'],
    fee: '$95',
    slots: ['8:30 AM', '12:00 PM', '3:45 PM'],
    avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=200&q=80',
    bio: 'Skin wellness made simple with gentle diagnostics and clear treatment guidance.',
  },
  {
    id: 4,
    name: 'Dr. Sanjay Menon',
    hospital: 'Wellness Care Hospital',
    department: 'Internal Medicine',
    rating: 4.85,
    experience: '18 years',
    languages: ['English', 'Hindi', 'Kannada'],
    fee: '$110',
    slots: ['9:30 AM', '12:15 PM', '5:00 PM'],
    avatar: 'https://images.unsplash.com/photo-1537368910025-700350fe46c7?auto=format&fit=crop&w=200&q=80',
    bio: 'Comprehensive adult care for chronic and preventive health management.',
  },
]

export const initialHealthProfile = {
  fullName: '',
  age: '',
  gender: '',
  dob: '',
  phone: '',
  email: '',
  bloodGroup: '',
  height: '',
  weight: '',
  bmi: '',
  allergies: '',
  conditions: '',
  medications: '',
  emergencyName: '',
  emergencyPhone: '',
}

export const languages = ['English', 'Hindi', 'Kannada', 'Tamil', 'Telugu']

export const dashboardCards = [
  { title: 'Health Score', value: '87', details: 'Above average for your age group', accent: 'primary' },
  { title: 'Recent Reports', value: '5 Files', details: 'Updated this month', accent: 'secondary' },
  { title: 'Next Appointment', value: 'Aug 12, 2026', details: 'Dr. Aisha Kapoor at 10:30 AM', accent: 'default' },
]
